resolver: lts-12.12

packages:
- .
- location:
    git: https://github.com/purescript/purescript.git
    # Version 0.12.2: https://github.com/purescript/purescript/commit/62f9b7f46f9caa3e4bec84d6df3ed50867503820
    commit: 62f9b7f46f9caa3e4bec84d6df3ed50867503820
  extra-dep: False
- location:
    git: https://github.com/purescript/psc-package.git
    # Version 0.5.1 https://github.com/purescript/psc-package/commit/93bf67d8738c0b6cfce209338dba9749a4a53415
    commit: 93bf67d8738c0b6cfce209338dba9749a4a53415
  extra-dep: false
- location:
    git: https://github.com/bitemyapp/esqueleto.git
    commit: 08c9b4cdf977d5bcd1baba046a007940c1940758
  extra-dep: true
- location:
    git: https://github.com/chrisdone/yesod-lucid
    commit: de8b455a6efcc02b95d5f6363a29044e230dc75f
  extra-dep: true
